### ISSUE TITLE
Unbound "system name" field breaks page

### ISSUE THREAD

**Issue by JAKeeney** [tekulvw/modularsecurity#134]
![image](https://user-images.githubusercontent.com/22156221/28339369-f71b6d88-6bd9-11e7-9eca-0d37e233804d.png)

**Comment by jdaless** [comment]
Do we have a desired character cap? If not that works too

**Comment by tekulvw** [comment]
1500 is max google is gonna support, I'd be more concerned with it breaking the screen than having an actual arbitrary limit.
