### ISSUE TITLE
Embedded research

### ISSUE THREAD

**Issue by tekulvw** [tekulvw/modularsecurity#18]
We need to know a few things:
- What OS should we put on the Pi? (and why)
- Is micropython sufficient for what we need or should we get the entire stdlib?
- How small can we make the firmware/OS size?
- Do we need drivers for the door sensor?
- How do we communicate from the door sensor?

**Comment by JAKeeney** [comment]
1. [Tiny Core](http://distro.ibiblio.org/tinycorelinux/intro.html) or MicroCore if we're feeling like we don't need a GUI. At about 10 MB, it's an OS so small that we can run off the RAM of a Raspberry Pi 0 W (only 48 MB of RAM are needed). If that's too absurdly small, [Lubuntu](http://lubuntu.net/) is also a commonly used lightweight distro that can be stored on a MicroSD card in the Raspberry Pi 0 W.

2. I'm pretty sure MicroPython includes all the libraries we would need to use.

3. There's a long list of lightweight Linux distros we can choose from, going as small as 7 MB. I don't think there will be much concern for running out of storage space as long as we use a big enough MicroSD card.

4. Don't believe so, [this guy](http://videos.cctvcamerapros.com/digital-io-alarm-in-out/send-push-notifications-from-raspberry-pi.html#wire-raspberry-pi) made more-or-less the same thing we're making and didn't mention anything about needing drivers.

5. We can communicate with [SQLite](https://www.sqlite.org). Other potential solutions can be found in [this](https://www.raspberrypi.org/forums/viewtopic.php?f=37&t=47793) thread.
