### ISSUE TITLE
Choose Pi OS and determine how to run a script on startup

### ISSUE THREAD

**Issue by tekulvw** [tekulvw/modularsecurity#26]

**Comment by JAKeeney** [comment]
We're going to be using Raspbian Jessie. A guide on how to run a file from startup can be found [here](https://askubuntu.com/questions/166777/how-can-you-make-a-sh-file-come-on-at-startup-in-lubuntu-12-04).

Here's the wifi setup link: https://davidmaitland.me/2015/12/raspberry-pi-zero-headless-setup/
